name: Lab 3 Create Artifact

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: Run tests & build app
        run: echo Pretend to build some kind of app...
      - name: Upload artifact to GitHub Package Registry
        uses: actions/upload-artifact@v3
        with:
          name: My artifact foo.txt
          path: foo.txt 
